import {clock,dateLabel,payroll,rupiah,useStoreWorkspace,wibDate} from './crewStoreWorkspace';

export default function CrewStoreDashboard({onGoAbsensi,onGoRiwayat}:{onGoAbsensi:()=>void;onGoRiwayat:()=>void}){
 const{data,loading,error}=useStoreWorkspace();if(loading)return <State text="Memuat dashboard Crew Store…"/>;if(error)return <State text={error} error/>;
 const today=wibDate(),schedule=data?.schedules.find(item=>item.schedule_date===today),attendance=data?.attendance.find(item=>item.attendance_date===today),summary=payroll(data),store=data?.assignment?.store;
 const action=attendance?.check_out?'Absensi Selesai':attendance?.check_in?'Clock Out Sekarang':'Clock In Sekarang';
 return <div className="p-4 sm:p-6 space-y-4"><section className="rounded-2xl bg-gradient-to-r from-emerald-600 to-teal-600 p-5 text-white"><p className="text-sm text-emerald-100">Selamat datang,</p><h1 className="text-2xl font-bold mt-1">{data?.crew.user?.full_name||'Crew Store'}</h1><p className="text-xs text-emerald-100 mt-1">{new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Jakarta'})} • {store?.name||'Crew Store'}</p></section>
 <section className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="p-4 border-b border-slate-100"><h2 className="font-semibold text-sm">Jadwal Hari Ini</h2></div>{schedule?<div className="p-4"><div className="grid sm:grid-cols-2 gap-3"><Schedule label="Jam Masuk" value={schedule.start_time.slice(0,5)}/><Schedule label="Jam Pulang" value={schedule.end_time.slice(0,5)}/></div><div className="mt-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="text-sm font-semibold">Status Absensi</p><p className="text-xs text-slate-500 mt-1">{attendance?.check_out?`Selesai ${clock(attendance.check_in)}–${clock(attendance.check_out)}`:attendance?.check_in?`Sudah Clock In ${clock(attendance.check_in)}`:'Belum Clock In'}</p></div><button disabled={!!attendance?.check_out} onClick={onGoAbsensi} className="px-4 py-2.5 rounded-xl bg-emerald-600 text-white text-sm font-semibold disabled:bg-slate-300">{action}</button></div></div>:<p className="p-7 text-center text-sm text-slate-500">Tidak ada jadwal kerja hari ini.</p>}</section>
 <div className="grid grid-cols-2 xl:grid-cols-4 gap-3"><Card label="Kehadiran Bulan Ini" value={`${summary.present} hari`} detail={`${summary.workDays} catatan ditinjau`} tone="blue"/><Card label="Keterlambatan" value={`${summary.lateMinutes} menit`} detail={`${rupiah(summary.deduction)} potongan`} tone="red"/><Card label="Lembur Disetujui" value={`${summary.overtimeHours} jam`} detail={`${rupiah(summary.bonus)} bonus`} tone="amber"/><Card label="Estimasi Payroll" value={rupiah(summary.total)} detail="Gaji pokok dan penyesuaian" tone="green"/></div>
 <section className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="p-4 border-b border-slate-100 flex justify-between"><h2 className="font-semibold text-sm">Riwayat Absensi Terbaru</h2><button onClick={onGoRiwayat} className="text-xs text-blue-600 font-semibold">Lihat semua</button></div><div className="divide-y divide-slate-100">{(data?.attendance||[]).slice(0,4).map(row=><div key={row.id} className="p-4 flex items-center gap-3"><div className="flex-1"><p className="text-sm font-medium">{dateLabel(row.attendance_date)}</p><p className="text-xs text-slate-500 mt-1 font-mono">{clock(row.check_in)} → {clock(row.check_out)}</p></div><span className={`text-xs px-2 py-1 rounded-full ${row.status==='LATE'?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{row.status==='LATE'?'Telat':row.status==='PRESENT'?'Tepat Waktu':row.status}</span>{row.overtime_status==='APPROVED'&&<span className="text-xs text-amber-700">+{Math.floor((row.overtime_minutes||0)/60)}j lembur</span>}</div>)}{!data?.attendance.length&&<p className="p-7 text-center text-sm text-slate-500">Belum ada riwayat absensi.</p>}</div></section></div>;
}
function State({text,error=false}:{text:string;error?:boolean}){return <div className="p-6"><p className={`rounded-2xl border p-5 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-slate-200 bg-white text-slate-600'}`}>{text}</p></div>}
function Schedule({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><strong className="block text-xl mt-1 font-mono">{value} WIB</strong></div>}
function Card({label,value,detail,tone}:{label:string;value:string;detail:string;tone:string}){const cls=tone==='red'?'bg-red-50 text-red-700':tone==='amber'?'bg-amber-50 text-amber-700':tone==='green'?'bg-emerald-50 text-emerald-700':'bg-blue-50 text-blue-700';return <div className={`rounded-2xl p-4 ${cls}`}><p className="text-xs opacity-70">{label}</p><strong className="block text-lg mt-1">{value}</strong><p className="text-xs mt-1 opacity-70">{detail}</p></div>}
