import { useEffect, useMemo, useState } from 'react';
import CameraPhotoUpload from '../../components/attendance/CameraPhotoUpload';
import { api } from '../../lib/apiClient';
import { CrewEventAssignment, idDate, rupiah, useCrewEventWorkspace } from './crewEventWorkspace';

type FormData = {
  transportasi_pergi_tanggal:string; transportasi_pergi_jam:string; transportasi_pergi_layanan:string; transportasi_pergi_kendaraan:string; transportasi_pergi_nominal:number; transportasi_pergi_photo:string;
  transportasi_pulang_tanggal:string; transportasi_pulang_jam:string; transportasi_pulang_layanan:string; transportasi_pulang_kendaraan:string; transportasi_pulang_nominal:number; transportasi_pulang_photo:string;
  tes_print_before_photo:string; tes_print_after_photo:string;
  omset_tunai:number; omset_transfer:number; omset_nominal_photo:string;
  kuota_nominal:number; kuota_gb:number; kuota_provider:string; kuota_catatan:string; kuota_nominal_photo:string;
};

const operationalKeys = ['transportasi_pergi_nominal','transportasi_pulang_nominal','transportasi_pergi_photo','transportasi_pulang_photo','tes_print_before_photo','tes_print_after_photo','kuota_nominal','omset_nominal'];
const numberValue = (value:unknown) => Number(value) || 0;

function fromWorkflow(row:CrewEventAssignment):FormData {
  const data = row.workflow.data || {};
  const schedules = [...(row.event_schedules || [])].sort((a,b)=>a.schedule_date.localeCompare(b.schedule_date));
  const legacyOmset = numberValue(data.omset_nominal);
  return {
    transportasi_pergi_tanggal:String(data.transportasi_pergi_tanggal || schedules[0]?.schedule_date || row.event.event_date), transportasi_pergi_jam:String(data.transportasi_pergi_jam || ''), transportasi_pergi_layanan:String(data.transportasi_pergi_layanan || ''), transportasi_pergi_kendaraan:String(data.transportasi_pergi_kendaraan || ''), transportasi_pergi_nominal:numberValue(data.transportasi_pergi_nominal), transportasi_pergi_photo:String(data.transportasi_pergi_photo || ''),
    transportasi_pulang_tanggal:String(data.transportasi_pulang_tanggal || schedules.at(-1)?.schedule_date || row.event.event_date), transportasi_pulang_jam:String(data.transportasi_pulang_jam || ''), transportasi_pulang_layanan:String(data.transportasi_pulang_layanan || ''), transportasi_pulang_kendaraan:String(data.transportasi_pulang_kendaraan || ''), transportasi_pulang_nominal:numberValue(data.transportasi_pulang_nominal), transportasi_pulang_photo:String(data.transportasi_pulang_photo || ''),
    tes_print_before_photo:String(data.tes_print_before_photo || data.tes_print_photo || ''), tes_print_after_photo:String(data.tes_print_after_photo || ''),
    omset_tunai:numberValue(data.omset_tunai) || (numberValue(data.omset_transfer) ? 0 : legacyOmset), omset_transfer:numberValue(data.omset_transfer), omset_nominal_photo:String(data.omset_nominal_photo || ''),
    kuota_nominal:numberValue(data.kuota_nominal), kuota_gb:numberValue(data.kuota_gb), kuota_provider:String(data.kuota_provider || ''), kuota_catatan:String(data.kuota_catatan || ''), kuota_nominal_photo:String(data.kuota_nominal_photo || ''),
  };
}

export default function CeOperasional() {
  const { data, loading, error, reload } = useCrewEventWorkspace();
  const rows = useMemo(()=>[...(data?.assignments || [])].sort((a,b)=>b.event.event_date.localeCompare(a.event.event_date)),[data]);
  const [eventId,setEventId]=useState('');
  const row=rows.find(item=>item.event.id===eventId)||rows.find(item=>operationalKeys.some(key=>key in (item.workflow.data||{})))||rows[0];
  const [form,setForm]=useState<FormData|null>(null); const [editing,setEditing]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  useEffect(()=>{if(row){setEventId(row.event.id);setForm(fromWorkflow(row));}},[row?.event.id,row?.workflow.updated_at]);
  if(loading)return <State text="Memuat operasional event…"/>; if(error)return <State text={error} error/>; if(!row||!form)return <State text="Belum ada event yang ditugaskan."/>;
  const transport=form.transportasi_pergi_nominal+form.transportasi_pulang_nominal; const omset=form.omset_tunai+form.omset_transfer; const expense=transport+form.kuota_nominal;
  const set=<K extends keyof FormData>(key:K,value:FormData[K])=>setForm(current=>current?{...current,[key]:value}:current);
  const save=async()=>{setSaving(true);setMessage('');try{await api.put(`/crew-event/events/${row.event.id}/workflow`,{data:{...row.workflow.data,...form,omset_nominal:omset},expectedUpdatedAt:row.workflow.updated_at || null,currentStep:row.workflow.current_step,maxReached:row.workflow.max_reached});setEditing(false);setMessage('Data operasional tersimpan dan diperbarui untuk seluruh anggota.');reload();}catch(reason){setMessage(reason instanceof Error?reason.message:'Data operasional gagal disimpan.');}finally{setSaving(false);}};
  return <div className="p-4 sm:p-6 space-y-4">
    <section className="bg-white border border-slate-200 rounded-2xl p-4 flex flex-wrap items-center gap-3"><div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-700 flex items-center justify-center"><BriefcaseIcon/></div><div className="min-w-0 flex-1"><h1 className="font-semibold">{row.event.event_name}</h1><p className="text-xs text-slate-500 mt-1">{row.event.event_code} • {idDate(row.event.event_date)}</p></div>{rows.length>1&&<select value={eventId} onChange={event=>setEventId(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm">{rows.map(item=><option key={item.event.id} value={item.event.id}>{item.event.event_name}</option>)}</select>}<button onClick={()=>{setForm(fromWorkflow(row));setEditing(value=>!value);setMessage('');}} className="rounded-xl border border-blue-200 px-4 py-2 text-sm font-semibold text-blue-700">{editing?'Batal':'Edit Data'}</button></section>
    {message&&<p className={`rounded-xl border px-4 py-3 text-sm ${message.includes('tersimpan')?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-red-200 bg-red-50 text-red-700'}`}>{message}</p>}
    <div className="grid lg:grid-cols-2 gap-4">
      <Panel title="Transportasi">{editing?<div className="grid sm:grid-cols-2 gap-3"><TransportEditor eventId={row.event.id} direction="pergi" form={form} set={set}/><TransportEditor eventId={row.event.id} direction="pulang" form={form} set={set}/></div>:<div><TransportRow eventId={row.event.id} direction="PERGI" date={form.transportasi_pergi_tanggal} time={form.transportasi_pergi_jam} service={form.transportasi_pergi_layanan} vehicle={form.transportasi_pergi_kendaraan} amount={form.transportasi_pergi_nominal} photo={form.transportasi_pergi_photo}/><TransportRow eventId={row.event.id} direction="PULANG" date={form.transportasi_pulang_tanggal} time={form.transportasi_pulang_jam} service={form.transportasi_pulang_layanan} vehicle={form.transportasi_pulang_kendaraan} amount={form.transportasi_pulang_nominal} photo={form.transportasi_pulang_photo}/><Line label="Total Transportasi" value={rupiah(transport)} strong/></div>}</Panel>
      <Panel title="Cek Print">{editing?<div className="grid sm:grid-cols-2 gap-3"><CameraPhotoUpload eventId={row.event.id} value={form.tes_print_before_photo} onChange={value=>set('tes_print_before_photo',value)} fieldLabel="Sebelum Event" buttonLabel="Buka kamera"/><CameraPhotoUpload eventId={row.event.id} value={form.tes_print_after_photo} onChange={value=>set('tes_print_after_photo',value)} fieldLabel="Sesudah Event" buttonLabel="Buka kamera"/></div>:<div className="grid grid-cols-2 gap-3"><Evidence eventId={row.event.id} label="Sebelum Event" photo={form.tes_print_before_photo}/><Evidence eventId={row.event.id} label="Sesudah Event" photo={form.tes_print_after_photo}/></div>}</Panel>
      <Panel title="Omset Event">{editing?<div className="space-y-3"><div className="grid sm:grid-cols-2 gap-3"><Field label="Tunai" type="number" value={form.omset_tunai} onChange={value=>set('omset_tunai',Number(value))}/><Field label="Transfer" type="number" value={form.omset_transfer} onChange={value=>set('omset_transfer',Number(value))}/></div><CameraPhotoUpload eventId={row.event.id} value={form.omset_nominal_photo} onChange={value=>set('omset_nominal_photo',value)} fieldLabel="Foto Bukti Omset" buttonLabel="Buka kamera"/></div>:<><Line label="Tunai" value={rupiah(form.omset_tunai)}/><Line label="Transfer" value={rupiah(form.omset_transfer)}/><Evidence eventId={row.event.id} label="Bukti Omset" photo={form.omset_nominal_photo}/></>}<Line label="Total Omset" value={rupiah(omset)} strong/><Line label="Pengeluaran Operasional" value={rupiah(expense)}/><Line label="Selisih" value={rupiah(omset-expense)} strong/></Panel>
      <Panel title="Kuota dan Perangkat">{editing?<div className="space-y-3"><Field label="Jumlah kuota (GB)" type="number" value={form.kuota_gb} onChange={value=>set('kuota_gb',Number(value))}/><Field label="Biaya kuota" type="number" value={form.kuota_nominal} onChange={value=>set('kuota_nominal',Number(value))}/><Field label="Provider atau perangkat" value={form.kuota_provider} onChange={value=>set('kuota_provider',value)}/><Field label="Catatan" value={form.kuota_catatan} onChange={value=>set('kuota_catatan',value)}/><CameraPhotoUpload eventId={row.event.id} value={form.kuota_nominal_photo} onChange={value=>set('kuota_nominal_photo',value)} fieldLabel="Foto Bukti Kuota" buttonLabel="Buka kamera"/></div>:<><Line label="Jumlah kuota" value={`${form.kuota_gb} GB`}/><Line label="Biaya kuota" value={rupiah(form.kuota_nominal)}/><Line label="Provider atau perangkat" value={form.kuota_provider||'Belum diisi'}/><Line label="Catatan" value={form.kuota_catatan||'Tidak ada catatan'}/><Evidence eventId={row.event.id} label="Bukti Kuota" photo={form.kuota_nominal_photo}/></>}</Panel>
    </div>{editing&&<div className="flex justify-end"><button disabled={saving} onClick={save} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white disabled:bg-slate-300">{saving?'Menyimpan…':'Simpan Perubahan'}</button></div>}
  </div>;
}

type Setter = <K extends keyof FormData>(key:K,value:FormData[K])=>void;
function TransportEditor({eventId,direction,form,set}:{eventId:string;direction:'pergi'|'pulang';form:FormData;set:Setter}){const prefix=`transportasi_${direction}_` as 'transportasi_pergi_'|'transportasi_pulang_';return <div className="rounded-xl bg-slate-50 p-3 space-y-2"><strong className="text-sm">{direction==='pergi'?'Pergi':'Pulang'}</strong><Field label="Tanggal" type="date" value={form[`${prefix}tanggal`]} onChange={value=>set(`${prefix}tanggal`,value)}/><Field label="Jam" type="time" value={form[`${prefix}jam`]} onChange={value=>set(`${prefix}jam`,value)}/><Field label="Layanan" value={form[`${prefix}layanan`]} onChange={value=>set(`${prefix}layanan`,value)}/><Field label="Kendaraan" value={form[`${prefix}kendaraan`]} onChange={value=>set(`${prefix}kendaraan`,value)}/><Field label="Biaya" type="number" value={form[`${prefix}nominal`]} onChange={value=>set(`${prefix}nominal`,Number(value))}/><CameraPhotoUpload eventId={eventId} value={form[`${prefix}photo`]} onChange={value=>set(`${prefix}photo`,value)} fieldLabel="Foto Bukti" buttonLabel="Buka kamera"/></div>}
function TransportRow({eventId,direction,date,time,service,vehicle,amount,photo}:{eventId:string;direction:string;date:string;time:string;service:string;vehicle:string;amount:number;photo:string}){return <div className="flex items-center gap-3 py-3 border-b border-slate-100"><PhotoThumb eventId={eventId} photo={photo}/><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold tracking-wide text-blue-600">{direction} <span className="font-mono text-slate-500">{time||'--:--'}</span></p><p className="text-sm font-medium text-slate-900 truncate">{service||'Layanan belum diisi'}</p><p className="text-xs text-slate-500 truncate">{vehicle||'Kendaraan belum diisi'} • {idDate(date)}</p></div><strong className="text-sm font-mono whitespace-nowrap">{rupiah(amount)}</strong></div>}
function Evidence({eventId,label,photo}:{eventId:string;label:string;photo:string}){return <div className="rounded-xl bg-slate-50 p-3"><PhotoThumb eventId={eventId} photo={photo} large/><p className="mt-2 text-xs font-medium text-slate-700">{label}</p><p className="text-[11px] text-slate-500">{photo?'Foto tersedia':'Belum ada foto'}</p></div>}
function PhotoThumb({eventId,photo,large=false}:{eventId:string;photo:string;large?:boolean}){const[url,setUrl]=useState('');useEffect(()=>{let active=true;if(!photo){setUrl('');return;}api.get<{url:string}>(`/crew-event/events/${eventId}/photos/url?key=${encodeURIComponent(photo)}`).then(result=>{if(active)setUrl(result.url)}).catch(()=>{});return()=>{active=false};},[eventId,photo]);return url?<img src={url} alt="Bukti" className={`${large?'w-full h-28':'w-12 h-12'} rounded-xl object-cover border border-slate-200`}/>:<div className={`${large?'w-full h-28':'w-12 h-12'} rounded-xl bg-slate-100 text-slate-400 flex items-center justify-center`}><CameraIcon/></div>}
function CameraIcon(){return <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.8} d="M3 7h4l2-3h6l2 3h4v13H3V7zm9 3a4 4 0 100 8 4 4 0 000-8z"/></svg>}
function BriefcaseIcon(){return <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.8} d="M9 6V4h6v2m-10 0h14a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2zm-2 5h18"/></svg>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><h2 className="p-4 border-b border-slate-100 font-semibold text-sm">{title}</h2><div className="p-4 space-y-1">{children}</div></section>}
function Line({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className="flex justify-between gap-4 py-3 border-b border-slate-100 last:border-0"><span className="text-sm text-slate-500">{label}</span><span className={`text-sm text-right ${strong?'font-bold':'font-medium'}`}>{value}</span></div>}
function Field({label,value,onChange,type='text'}:{label:string;value:string|number;onChange:(value:string)=>void;type?:string}){return <label className="block text-sm text-slate-600">{label}<input type={type} min={type==='number'?0:undefined} value={value} onChange={event=>onChange(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-slate-900"/></label>}
function State({text,error=false}:{text:string;error?:boolean}){return <div className="p-6"><p className={`rounded-2xl border p-5 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-slate-200 bg-white text-slate-600'}`}>{text}</p></div>}
