const test=require('node:test'),assert=require('node:assert/strict');let mode='store',open=null;const queries=[];
const newStore={id:'new-schedule',schedule_date:'2026-09-07',start_time:'09:00',end_time:'18:00',store_assignment:{id:'new-assignment',status:'ACTIVE',start_date:'2026-09-02',end_date:null,store:{name:'Sukor',status:'ACTIVE'}}};
const db={from(table){const filters={};const q={select(){return q},eq(k,v){filters[k]=v;return q},not(){return q},is(k,v){filters[k]=v;return q},lte(){return q},or(){return q},in(){return q},order(){return q},limit(){return q},async maybeSingle(){queries.push({table,filters});if(table==='crew')return {data:{id:'crew',crew_type:mode==='store'?'CREW_STORE':'CREW_EVENT',status:'ACTIVE'}};if(table==='attendance_logs')return {data:Object.hasOwn(filters,'check_out')?open:null};if(table==='store_schedules'){assert.equal(filters['store_assignment.status'],'ACTIVE');return {data:newStore}};if(table==='event_schedules')return {data:{id:'event-schedule',start_time:'10:00',end_time:'17:00',event_assignment:{id:'event-assignment',event:{id:'event',event_name:'Event Sukor'}}}};return {data:null}}};return q;}};
for(const [file,value] of [['../src/config/supabaseClient',db],['../src/utils/signedUrl',{}]]){const p=require.resolve(file);require.cache[p]={id:p,filename:p,loaded:true,exports:value};}
const controller=require('../src/modules/attendance/attendance.controller');
async function today(){let result;await controller.today({user:{id:'user'}},{json(data){result=data},status(){return this}},error=>{throw error});return result;}
test('new store assignment is selected and old completed attendance cannot block it',async()=>{mode='store';open=null;const r=await today();assert.equal(r.context.locationName,'Sukor');assert.equal(r.context.storeAssignmentId,'new-assignment');assert.equal(r.attendance,null);assert.ok(queries.some(q=>q.filters.store_schedule_id==='new-schedule'));});
test('open attendance retains original store for clock out after transfer',async()=>{open={id:'open',check_in:'2026-09-07T02:00:00Z',store_assignment_id:'old',store_schedule_id:'old-schedule',store_schedule:{start_time:'09:00',end_time:'18:00'},store_assignment:{store:{name:'Gacoan'}}};const r=await today();assert.equal(r.context.locationName,'Gacoan');assert.equal(r.attendance.id,'open');assert.equal(r.context.storeAssignmentId,'old');open=null;});
test('new event uses its own assignment and schedule',async()=>{mode='event';const r=await today();assert.equal(r.context.eventId,'event');assert.equal(r.context.eventAssignmentId,'event-assignment');assert.equal(r.context.scheduledStart,'10:00');assert.ok(queries.some(q=>q.filters.event_schedule_id==='event-schedule'));});
