const test=require('node:test'),assert=require('node:assert/strict'),express=require('express');
const id='00000000-0000-4000-8000-000000000001';const workflow={event_id:id,data:{kuota_gb:50},current_step:9,max_reached:9,updated_at:'2026-09-07'};
const dbPath=require.resolve('../src/config/supabaseClient'),signedPath=require.resolve('../src/utils/signedUrl');let signed=[];
require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:{from(table){const q={select(){return q},eq(){return q},or(){return q},order(){return q},limit(){return q},range(){return Promise.resolve({data:[],error:null})},maybeSingle(){return Promise.resolve({data:table==='events'?{id,status:'ONGOING'}:workflow,error:null})},then(resolve){return Promise.resolve({data:[],error:null}).then(resolve)}};return q;}}};
require.cache[signedPath]={id:signedPath,filename:signedPath,loaded:true,exports:{getSignedDownloadUrl:async(key)=>{signed.push(key);return 'https://example.test/photo'}}};
const router=require('../src/modules/events/adminEvents.routes');
async function request(path,role='SUPER_ADMIN'){const app=express();app.use((req,res,next)=>{req.role=role;next()});app.use(router);app.use((error,req,res,next)=>res.status(error.status||500).json({message:error.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{const res=await fetch(`http://127.0.0.1:${server.address().port}${path}`);return {status:res.status,body:await res.json()}}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
test('admin detail reads shared workflow and canonical event status',async()=>{const r=await request('/'+id);assert.equal(r.status,200);assert.deepEqual(r.body.workflow,workflow);assert.equal(r.body.status,'ONGOING')});
test('crew cannot use admin detail or photo endpoint',async()=>{assert.equal((await request('/'+id,'CREW_EVENT')).status,403);assert.equal((await request(`/${id}/photos/url?key=x`,'CREW_EVENT')).status,403)});
test('photo signing rejects other event photos',async()=>{assert.equal((await request(`/${id}/photos/url?key=event-workflows/another/photo.jpg`)).status,403);assert.equal(signed.length,0);assert.equal((await request(`/${id}/photos/url?key=event-workflows/${id}/photo.jpg`)).status,200);assert.equal(signed.length,1)});
