const test=require('node:test'),assert=require('node:assert/strict');
const express=require('express');
const {installSecurity,validateEnvironment}=require('../../src/security/http');
async function run(fn){const app=express();installSecurity(app,{production:false,origins:['https://app.example.com'],limit:2});app.post('/api/test',(req,res)=>res.json({ok:true}));app.use(require('../../src/middlewares/errorHandler'));const s=app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));try{await fn(`http://127.0.0.1:${s.address().port}`)}finally{await new Promise(r=>s.close(r));}}
const headers={'Content-Type':'application/json','X-FotoSnaps-Request':'1',Origin:'https://app.example.com'};
test('reject foreign origins and simple cross-site forms before mutation',()=>run(async base=>{assert.equal((await fetch(base+'/api/test',{method:'POST',headers:{...headers,Origin:'https://evil.example'},body:'{}'})).status,403);assert.equal((await fetch(base+'/api/test',{method:'POST',headers:{'Content-Type':'text/plain'},body:'{}'})).status,403);}));
test('allow intended client and enforce rate limit with retry header',()=>run(async base=>{for(let i=0;i<2;i++)assert.equal((await fetch(base+'/api/test',{method:'POST',headers,body:'{}'})).status,200);const r=await fetch(base+'/api/test',{method:'POST',headers,body:'{}'});assert.equal(r.status,429);assert.ok(r.headers.get('retry-after'));}));
test('reject prototype keys and oversized bodies',()=>run(async base=>{assert.equal((await fetch(base+'/api/test',{method:'POST',headers,body:'{"__proto__":{"admin":true}}'})).status,400);assert.equal((await fetch(base+'/api/test',{method:'POST',headers,body:JSON.stringify({data:'x'.repeat(300000)})})).status,413);}));
test('deny dotfiles and do not expose stack or SQL errors',()=>run(async base=>{assert.equal((await fetch(base+'/.git/config')).status,404);assert.equal((await fetch(base+'/.env')).status,404);}));
test('production refuses insecure configuration',()=>{assert.throws(()=>validateEnvironment({NODE_ENV:'production'}));assert.throws(()=>validateEnvironment({NODE_ENV:'production',CORS_ORIGIN:'*'}));});
test('production refuses plaintext even with spoofed forwarded proto',async()=>{const app=express();installSecurity(app,{production:true,origins:['https://app.example.com']});app.get('/api/test',(req,res)=>res.json({ok:true}));const s=app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));try{assert.equal((await fetch(`http://127.0.0.1:${s.address().port}/api/test`,{headers:{'X-Forwarded-Proto':'https'}})).status,400);}finally{await new Promise(r=>s.close(r));}});
