import {useEffect,useState} from 'react';
import {api} from '../../lib/apiClient';
import {rupiah} from '../../pages/crewEvent/crewEventWorkspace';
export function EventPhoto({eventId,value,label,admin=false}:{eventId:string;value?:string;label:string;admin?:boolean}){
 const [url,setUrl]=useState(''),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;setUrl('');setFailed(false);if(value)api.get<{url:string}>(`${admin?'/admin-events':'/crew-event/events'}/${eventId}/photos/url?key=${encodeURIComponent(value)}`).then(r=>{if(active)setUrl(r.url)}).catch(()=>{if(active)setFailed(true)});return()=>{active=false}},[eventId,value,admin]);
 return <figure className="space-y-2"><figcaption className="text-xs text-slate-500">{label}</figcaption>{url?<a href={url} target="_blank" rel="noreferrer"><img src={url} alt={label} className="h-32 w-full rounded-xl object-contain bg-slate-50"/></a>:<p className="text-xs text-slate-500 p-3 bg-slate-50 rounded-xl">{failed?'Foto gagal dimuat':value?'Memuat foto…':'Belum ada foto'}</p>}</figure>;
}
export default function EventResults({eventId,data,tab,admin=false}:{eventId:string;data:Record<string,any>;tab:'Inventory'|'Operasional';admin?:boolean}){
 const photo=(value:string,label:string)=><EventPhoto eventId={eventId} value={value} label={label} admin={admin}/>;
 if(tab==='Inventory'){
 const before=Array.isArray(data.inventory_before_items)?data.inventory_before_items:[],after=Array.isArray(data.inventory_after_items)?data.inventory_after_items:[];
 return <div className="space-y-4">{!before.length&&<p className="text-sm text-slate-500">Crew belum menyimpan inventory.</p>}{before.map((item:any,i:number)=>{const end=after[i];return <section key={i} className="rounded-xl border border-slate-200 p-4 space-y-3"><h3 className="font-semibold">{item.nama} • {item.kategori}</h3><p className="text-sm">Sebelum: {item.jumlah} • Sesudah: {end?end.jumlah:'Belum diisi'} • Selisih: {end?Number(end.jumlah)-Number(item.jumlah):'Belum dapat dihitung'}</p><p className="text-sm">Kondisi: {item.kondisi} → {end?.kondisi||'Belum diisi'}{end?.alasan?` • ${end.alasan}`:''}</p><div className="grid grid-cols-2 gap-3">{photo(item.foto,'Sebelum event')}{photo(end?.foto_after,'Sesudah event')}</div></section>})}</div>;
 }
 const n=(key:string)=>Number(data[key])||0,omset=data.omset_tunai!==undefined||data.omset_transfer!==undefined?n('omset_tunai')+n('omset_transfer'):n('omset_nominal'),cost=n('transportasi_pergi_nominal')+n('transportasi_pulang_nominal')+n('kuota_nominal');
 return <div className="grid md:grid-cols-2 gap-4"><section className="rounded-xl border border-slate-200 p-4 space-y-3"><h3 className="font-semibold">Transportasi</h3>{(['pergi','pulang'] as const).map(dir=><div key={dir} className="border-b border-slate-100 pb-3"><strong className="capitalize">{dir} • {rupiah(n(`transportasi_${dir}_nominal`))}</strong><p className="text-sm">{data[`transportasi_${dir}_tanggal`]||'Tanggal belum diisi'} • {data[`transportasi_${dir}_jam`]||'Jam belum diisi'} WIB</p><p className="text-sm">{data[`transportasi_${dir}_layanan`]||'Layanan belum diisi'} • {data[`transportasi_${dir}_kendaraan`]||'Kendaraan belum diisi'}</p>{photo(data[`transportasi_${dir}_photo`],`Bukti ${dir}`)}</div>)}<p>Total: {rupiah(n('transportasi_pergi_nominal')+n('transportasi_pulang_nominal'))}</p></section><section className="rounded-xl border border-slate-200 p-4 space-y-3"><h3 className="font-semibold">Cek Print</h3>{photo(data.tes_print_before_photo||data.tes_print_photo,'Sebelum event')}{photo(data.tes_print_after_photo,'Sesudah event')}</section><section className="rounded-xl border border-slate-200 p-4 space-y-3"><h3 className="font-semibold">Kuota / Orbit</h3><p>{n('kuota_gb')} GB • {rupiah(n('kuota_nominal'))}</p><p>{data.kuota_provider||'Provider belum diisi'}</p><p>{data.kuota_catatan||'Tidak ada catatan'}</p>{photo(data.kuota_nominal_photo,'Bukti kuota')}</section><section className="rounded-xl border border-slate-200 p-4 space-y-3"><h3 className="font-semibold">Omset Event</h3><p>Tunai: {rupiah(n('omset_tunai'))}</p><p>Transfer: {rupiah(n('omset_transfer'))}</p><p>Total omset: {rupiah(omset)}</p><p>Pengeluaran: {rupiah(cost)}</p><p>Selisih: {rupiah(omset-cost)}</p>{photo(data.omset_nominal_photo,'Bukti omset')}</section></div>;
}
