const { chromium } = require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES + '/playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve('dist');
const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname;const file=path.join(root,p==='/'?'index.html':p);fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.jpg')?'image/jpeg':'text/html');res.end(data);});});
(async()=>{const binary=(await import(process.env.CHROMIUM_MODULE)).default;await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;let browser;
try{browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||await binary.executablePath(),args:binary.args});const page=await browser.newPage({viewport:{width:360,height:800},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const workflow={event_id:'event-1',data:{inventory_before_items:[{nama:'Kamera',jumlah:2,kategori:'Electronic',kondisi:'Baik'}],inventory_after_items:[{nama:'Kamera',jumlah:2,kondisi:'Baik'}],transportasi_pergi_nominal:50000,tes_print_jumlah:2,omset_nominal:500000},current_step:5,max_reached:5,updated_at:'2026-09-01T03:00:00Z'};
const workspace={crew:{id:'crew-1',employee_code:'BDG-EVT-1',base_salary:2000000,user:{full_name:'Crew Bandung'}},assignments:[{id:'assignment-1',position:'PIC',status:'ACTIVE',event:{id:'event-1',event_code:'BDG-SMA1',event_name:'Event SMA 1 Bandung',client_name:'SMA 1',event_date:'2026-09-01',status:'ONGOING',branch:{name:'Bandung'},event_locations:[{address:'SMA 1 Bandung'}],pic:{user:{full_name:'Crew Bandung'}}},event_schedules:[{id:'schedule-1',schedule_date:'2026-09-01',start_time:'08:00:00',end_time:'17:00:00',status:'ACTIVE'}],workflow,team:['Crew Bandung','Crew Dua'],attendance:[]}]};
await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin===origin)return route.continue();if(!url.pathname.startsWith('/api/'))return route.abort();let data={};if(url.pathname==='/api/auth/login')data={token:'fixture',refreshToken:'refresh',user:{id:'user-1',full_name:'Crew Bandung',email:'crew@test.local'},role:'CREW_EVENT'};else if(url.pathname==='/api/users/me')data={id:'user-1',full_name:'Crew Bandung',email:'crew@test.local'};else if(url.pathname==='/api/crew-event/workspace')data=workspace;else if(url.pathname==='/api/crew-event/events/event-1/workflow')data=workflow;else if(url.pathname==='/api/notifications')data=[];else if(url.pathname==='/api/attendance')data=[];else if(url.pathname==='/api/attendance/calendar')data={days:[]};else if(url.pathname==='/api/attendance/today')data={crewId:'crew-1',hasSchedule:false,context:null,attendance:null};else if(url.pathname==='/api/auth/logout')data={message:'ok'};return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});});
await page.goto(origin);await page.locator('#email').fill('crew@test.local');await page.locator('#password').fill('password-uji');await page.getByRole('button',{name:'Log in',exact:true}).click();await page.getByText('Event SMA 1 Bandung',{exact:true}).waitFor();
const nav=page.getByRole('navigation',{name:'Navigasi karyawan'});
for(const width of [360,390,430]){
 await page.setViewportSize({width,height:800});await nav.getByRole('button',{name:'Event',exact:true}).click();await page.locator('main').getByRole('heading',{name:'Event Saya',exact:true}).waitFor();
 assert.ok(await nav.isVisible());assert.ok(await page.locator('main').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 for(const button of await nav.getByRole('button').all()){const box=await button.boundingBox();assert.ok(box.height>=44);}
 await page.getByRole('button',{name:'Edit Workflow',exact:true}).click();await page.getByLabel('Pilih langkah workflow').waitFor();
 assert.ok(await page.locator('main').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 await page.screenshot({path:`/tmp/fotosnaps-mobile-${width}.png`});
 await nav.getByRole('button',{name:'Absensi',exact:true}).click();
 await nav.getByRole('button',{name:'Menu',exact:true}).click();await page.locator('aside:visible').getByRole('button',{name:'Operasional',exact:true}).click();
 await page.getByText('Total Omset',{exact:true}).waitFor();assert.ok(await page.locator('main').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
}
await page.setViewportSize({width:1365,height:900});assert.equal(await nav.isVisible(),false);assert.ok(await page.locator('aside:visible').count());assert.deepEqual(errors,[]);console.log('PASS: 360/390/430 mobile navigation, workflow, operational layout; desktop sidebar.');
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(error=>{console.error(error);process.exitCode=1;});
