// Isolated HTTP fixtures; never calls production services.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve('dist'),out=process.env.QA_OUTPUT_DIR||'/tmp/jawara-update-qa';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname;fs.readFile(path.join(root,p==='/'?'index.html':p),(e,data)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.jpg')?'image/jpeg':'text/html');res.end(data);});});
const branch={id:'branch-1',name:'Blok M',city_name:'Jakarta',code:'JKT'},user={id:'user-1',full_name:'Crew Uji',email:'crew@example.test',company_name:'JAWARA',job_title:'Fotografer',branch_name:'Jakarta / Blok M'};
const workflow={event_id:'event-1',current_step:15,max_reached:15,updated_at:'2026-09-14T03:00:00Z',data:{inventory_before_items:[{nama:'Kamera',jumlah:2,kategori:'Electronic',kondisi:'Baik'}],inventory_after_items:[{nama:'Kamera',jumlah:2,kondisi:'Baik'}],transportasi_pergi_nominal:50000,transportasi_pulang_nominal:50000,kuota_nominal:15000,kuota_gb:3,omset_tunai:700000,omset_transfer:200000}};
const crew={id:'crew-1',employee_code:'C01',company_name:'JAWARA',job_title:'Fotografer',crew_type:'CREW_EVENT',branch_id:branch.id,branch,status:'ACTIVE',base_salary:80000,user,store_assignments:[],event_assignments:[]};
const event={id:'event-1',company_name:'JAWARA',event_code:'EV01',event_name:'Event Pengujian',event_date:'2026-09-14',start_time:'08:00:00',end_time:'17:00:00',status:'COMPLETED',client_name:'Klien Uji',branch,branch_id:branch.id,pic_crew_id:crew.id,pic:{user},event_locations:[{address:'Blok M, Jakarta'}],event_assignments:[],workflow,attendance:[],audit:[{id:'audit-1',action:'WORKFLOW_COMPLETED',created_at:'2026-09-14T03:00:00Z',actor_name:'Crew Uji',subject_name:'Event Pengujian'}]};
const assignment={id:'assignment-1',position:'Fotobox',status:'ENDED',event,event_schedules:[],workflow,team:[],members:[{id:'assignment-1',crew_id:crew.id,name:user.full_name,company_name:'JAWARA',job_title:'Fotografer',position:'Fotobox',status:'ENDED'}],attendance:[]};
let browser,context,origin;
async function nav(page,name){if(await page.getByRole('button',{name:'Buka menu',exact:true}).isVisible())await page.getByRole('button',{name:'Buka menu',exact:true}).click();await page.locator('aside:visible').getByRole('button',{name,exact:true}).click();}
async function mockPage(role){
 const page=await context.newPage();await page.setViewportSize({width:1365,height:900});page.setDefaultTimeout(12000);const errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));
 let guests=[{id:'guest-1',full_name:'Guest Uji',phone:'081234567890',company_name:'JAWARA',job_title:'Fotografer',assignment_kind:'OFFICE',crew_type:'CREW_STORE',location_name:'Kantor · Jakarta · Blok M',clock_type:'IN',occurred_at:'2026-09-14T02:00:00Z',review_status:'PENDING'}];
 await page.route('**/*',async r=>{const u=new URL(r.request().url()),p=u.pathname,m=r.request().method();if(u.origin===origin)return r.continue();if(!p.startsWith('/api/'))return r.abort();if(m!=='GET')writes.push({path:p,method:m,body:r.request().postData()});let data=[];
 if(p==='/api/auth/login')data={token:'fixture',refreshToken:'fixture-refresh',user,role};else if(p==='/api/users/me')data=user;
 else if(p==='/api/crew-event/workspace')data={crew,assignments:[assignment]};else if(p==='/api/crew-event/events/event-1/workflow')data=workflow;
 else if(p==='/api/admin-directory')data={branches:[branch],stores:[],events:[event],archivedStores:[]};else if(p==='/api/crew')data=[crew];else if(p==='/api/admin-events')data=[event];else if(p==='/api/admin-events/event-1')data=event;
 else if(p==='/api/admin-attendance')data={registered:[],guest:guests};else if(p==='/api/admin-attendance/guest/guest-1'&&m==='DELETE'){guests=[];data={message:'Absensi dihapus.'};}else if(p.endsWith('/photos/url'))data={url:''};
 await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});});
 await page.goto(origin);await page.locator('#email').fill(user.email);await page.locator('#password').fill('test-password');await page.getByRole('button',{name:'Log in',exact:true}).click();await page.locator('main').waitFor();return {page,errors,writes};
}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 const binary=process.env.CHROMIUM_MODULE?(await import(process.env.CHROMIUM_MODULE)).default:null;
 browser=await chromium.launch({headless:true,...(binary?{executablePath:process.env.CHROMIUM_EXECUTABLE||await binary.executablePath(),args:binary.args}:{})});
 context=await browser.newContext();
 try{
 const {page,errors,writes}=await mockPage('CREW_EVENT');await nav(page,'Dashboard');const identity=page.getByRole('region',{name:'Identitas pekerjaan'});await identity.waitFor();await page.waitForFunction(()=>document.querySelector('[aria-label="Identitas pekerjaan"]')?.textContent.includes('Jakarta / Blok M'));const welcome=page.locator('main section').filter({hasText:'Selamat datang,'}).first();assert.ok((await identity.boundingBox()).y>(await welcome.boundingBox()).y);
 await nav(page,'Inventory');await page.getByText('Inventory Sebelum dan Setelah Event',{exact:true}).waitFor();assert.equal(await identity.count(),0);assert.equal(await page.getByRole('button',{name:/Edit/}).count(),0);await page.getByRole('button',{name:'Lihat foto',exact:true}).click();await page.getByText('Sebelum event',{exact:true}).waitFor();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export Excel',exact:true}).click();await(await download).saveAs(out+'/inventory.xlsx');
 await nav(page,'Operasional');await page.getByText('Total Omset',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:/Edit/}).count(),0);assert.ok((await page.locator('main').innerText()).includes('900.000'));await page.screenshot({path:out+'/crew-operasional.png'});
 await nav(page,'Event Saya');await page.getByRole('button',{name:'Detail Event',exact:true}).click();await page.getByText('Anggota Event',{exact:true}).waitFor();assert.equal(await identity.count(),0);await page.screenshot({path:out+'/crew-event-detail.png'});
 await page.getByRole('button',{name:'Tinjau Workflow',exact:true}).click();await page.getByRole('heading',{name:'Tinjau Workflow',exact:true}).waitFor();const pdf=page.waitForEvent('download');await page.getByRole('button',{name:'Export PDF',exact:true}).first().click();await(await pdf).saveAs(out+'/event-report.pdf');assert.equal(await page.locator('main input,main textarea').count(),0);assert.equal(await page.getByRole('button',{name:/Edit|Simpan/}).count(),0);await page.setViewportSize({width:375,height:812});await page.screenshot({path:out+'/crew-review-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(writes.filter(w=>/workflow|photos|checkpoints/.test(w.path)).length,0);assert.deepEqual(errors,[]);
 const admin=await mockPage('SUPER_ADMIN');await nav(admin.page,'Kelola Event');await admin.page.getByRole('button',{name:'Detail',exact:true}).click();await admin.page.getByRole('tab',{name:'Audit Log',exact:true}).click();await admin.page.getByRole('columnheader',{name:'Pelaku',exact:true}).waitFor();await admin.page.getByRole('cell',{name:'Crew Uji',exact:true}).waitFor();
 await admin.page.getByRole('tab',{name:'Operasional',exact:true}).click();await admin.page.getByText('Total Omset',{exact:true}).waitFor();await admin.page.screenshot({path:out+'/admin-event-operasional.png'});
 await nav(admin.page,'Absensi');await admin.page.getByRole('button',{name:'Hapus',exact:true}).click();const modal=admin.page.getByRole('dialog');await modal.locator('textarea').fill('Menghapus data pengujian');await modal.getByRole('button',{name:'Hapus Absensi',exact:true}).click();await modal.waitFor({state:'hidden'});assert.equal(admin.writes.filter(w=>w.method==='DELETE').length,1);assert.ok(admin.writes.find(w=>w.method==='DELETE').body.includes('Menghapus data pengujian'));await admin.page.getByRole('button',{name:'Muat ulang',exact:true}).click();assert.equal(await admin.page.getByRole('button',{name:'Hapus',exact:true}).count(),0);assert.deepEqual(admin.errors,[]);
 console.log('PASS: identity below welcome, readonly event results/workflow, mobile, Excel download, admin named audit, attendance deletion.');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
