import {submitScheduleRange} from '../../lib/scheduleRange';
import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {api} from '../../lib/apiClient';
import {control,message,primary} from './adminData';

interface Store {id:string;name:string;status:string}
interface CalendarResult {holidays:Holiday[];warnings:string[]}
interface Holiday {holiday_date:string;name:string;kind:'NATIONAL_HOLIDAY'|'COLLECTIVE_LEAVE'}
interface Result {warnings?:string[];created:number;crewCount:number;skippedHoliday:number;skippedExisting:number;skippedEvent:number;skippedDay:number}
const DAYS=[{value:0,label:'Min'},{value:1,label:'Sen'},{value:2,label:'Sel'},{value:3,label:'Rab'},{value:4,label:'Kam'},{value:5,label:'Jum'},{value:6,label:'Sab'}];

export default function BulkStoreScheduleManager({stores}:{stores:Store[]}){
 const [form,setForm]=useState({storeId:'',startDate:'',endDate:'',startTime:'09:00',endTime:'18:00',lateToleranceMinutes:'0',overtimePreapproved:false,workDays:[1,2,3,4,5,6]});
 const [holidays,setHolidays]=useState<Holiday[]>([]),[busy,setBusy]=useState(false),[syncing,setSyncing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function loadHolidays(){if(!form.startDate||!form.endDate){setHolidays([]);return;}const rows=await api.get<CalendarResult>(`/admin-store-schedules/holidays?from=${form.startDate}&to=${form.endDate}&metadata=true`);setHolidays(rows.holidays);setNotice(rows.warnings.join(" "));}
 useEffect(()=>{if(!form.startDate||!form.endDate){setHolidays([]);return;}let active=true;api.get<CalendarResult>(`/admin-store-schedules/holidays?from=${form.startDate}&to=${form.endDate}&metadata=true`).then(rows=>{if(active){setHolidays(rows.holidays);setNotice(rows.warnings.join(" "));setError('')}}).catch(reason=>{if(active)setError(message(reason))});return()=>{active=false};},[form.startDate,form.endDate]);
 const holidayMap=useMemo(()=>new Map(holidays.map(row=>[row.holiday_date,row])),[holidays]);
 function toggle(day:number){setForm(previous=>({...previous,workDays:previous.workDays.includes(day)?previous.workDays.filter(value=>value!==day):[...previous.workDays,day].sort()}));}
 async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await submitScheduleRange(body=>api.post<Result>('/admin-store-schedules/bulk',body),{...form,lateToleranceMinutes:Number(form.lateToleranceMinutes)},setNotice);setNotice(`${result.created} jadwal untuk ${result.crewCount} crew dibuat. ${result.skippedHoliday} tanggal libur, ${result.skippedExisting} jadwal lama, dan ${result.skippedEvent} benturan event dilewati. ${(result.warnings||[]).join(' ')}`);}catch(reason){setError(message(reason));}finally{setBusy(false);}}
 async function syncCalendar(){const start=Number((form.startDate||new Date().toISOString().slice(0,10)).slice(0,4)),end=Number((form.endDate||form.startDate||new Date().toISOString().slice(0,10)).slice(0,4));setSyncing(true);setError('');setNotice('');try{const notes:string[]=[];for(let year=start;year<=end;year++){setNotice(`Menyinkronkan kalender ${year}…`);const result=await api.post<{row_count:number;fallback:boolean;warning?:string}>('/admin-store-schedules/holidays/sync',{year});notes.push(result.warning||`Kalender ${year}: ${result.row_count} tanggal libur.`);}await loadHolidays();setNotice(notes.join(' '));}catch(reason){setError(message(reason));}finally{setSyncing(false);}}

 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">Pilih satu Store untuk membuat jadwal semua Crew Store aktif sekaligus. Jadwal per crew yang sudah ada tetap dipertahankan.</p><button type="button" onClick={syncCalendar} disabled={syncing} className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-sm font-medium text-blue-700 disabled:opacity-50">{syncing?'Menyinkronkan...':'Sinkronkan Kalender Rentang'}</button></div>
  {error?<p role="alert" className="ui-error rounded-xl p-3 text-sm">{error}</p>:null}{notice?<p role="status" className="ui-success rounded-xl p-3 text-sm">{notice}</p>:null}
  <form onSubmit={save} className="grid sm:grid-cols-2 gap-3 rounded-xl border border-slate-200 p-4">
   <label className="sm:col-span-2 text-xs text-slate-600">Store<select required className={control} value={form.storeId} onChange={event=>setForm({...form,storeId:event.target.value})}><option value="">Pilih Store</option>{stores.filter(store=>store.status==='ACTIVE').map(store=><option key={store.id} value={store.id}>{store.name}</option>)}</select></label>
   <label className="text-xs text-slate-600">Tanggal mulai<input required type="date" className={control} value={form.startDate} onChange={event=>setForm({...form,startDate:event.target.value})}/></label>
   <label className="text-xs text-slate-600">Tanggal selesai<input required type="date" min={form.startDate} className={control} value={form.endDate} onChange={event=>setForm({...form,endDate:event.target.value})}/></label>
   <fieldset className="sm:col-span-2"><legend className="mb-2 text-xs text-slate-600">Hari kerja</legend><div className="flex flex-wrap gap-2">{DAYS.map(day=><label key={day.value} className={`cursor-pointer rounded-xl border px-3 py-2 text-sm ${form.workDays.includes(day.value)?'border-blue-500 bg-blue-50 text-blue-700':'border-slate-200 text-slate-500'}`}><input type="checkbox" className="sr-only" checked={form.workDays.includes(day.value)} onChange={()=>toggle(day.value)}/>{day.label}</label>)}</div><p className="mt-2 text-xs text-slate-500">Minggu dapat dipilih sebagai hari kerja. Hanya libur nasional dan cuti bersama yang dilewati otomatis.</p></fieldset>
   <label className="text-xs text-slate-600">Jam masuk<input required type="time" className={control} value={form.startTime} onChange={event=>setForm({...form,startTime:event.target.value})}/></label>
   <label className="text-xs text-slate-600">Jam pulang<input required type="time" className={control} value={form.endTime} onChange={event=>setForm({...form,endTime:event.target.value})}/></label>
   <label className="sm:col-span-2 text-xs text-slate-600">Toleransi telat (menit)<input required type="number" min="0" max="240" className={control} value={form.lateToleranceMinutes} onChange={event=>setForm({...form,lateToleranceMinutes:event.target.value})}/></label>
   <label className="sm:col-span-2 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><input type="checkbox" className="mt-1" checked={form.overtimePreapproved} onChange={event=>setForm({...form,overtimePreapproved:event.target.checked})}/><span><strong>Setujui lembur dari jadwal</strong><small className="mt-1 block">Jika tidak dicentang, lembur tetap menunggu keputusan admin.</small></span></label>
   <button disabled={busy||!form.workDays.length} className={primary+' sm:col-span-2'}>{busy?'Membuat jadwal...':'Buat Jadwal Semua Crew Store'}</button>
  </form>
  {form.startDate?<CalendarPreview startDate={form.startDate} endDate={form.endDate||form.startDate} workDays={form.workDays} holidays={holidayMap}/>:null}
  {holidays.length?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><strong className="text-sm text-amber-900">Libur dalam rentang</strong><ul className="mt-2 space-y-1 text-xs text-amber-800">{holidays.map(row=><li key={row.holiday_date}>{row.holiday_date} • {row.name}</li>)}</ul></div>:null}
 </div>;
}

function CalendarPreview({startDate,endDate,workDays,holidays}:{startDate:string;endDate:string;workDays:number[];holidays:Map<string,Holiday>}){
 const [year,month]=startDate.split('-').map(Number),first=new Date(Date.UTC(year,month-1,1)),offset=first.getUTCDay(),count=new Date(Date.UTC(year,month,0)).getUTCDate();
 const monthName=first.toLocaleDateString('id-ID',{timeZone:'UTC',month:'long',year:'numeric'});
 return <section className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="text-sm font-semibold text-slate-900">Kalender {monthName}</h3><div className="mt-3 grid grid-cols-7 gap-1">{['Min','Sen','Sel','Rab','Kam','Jum','Sab'].map(day=><span key={day} className="py-1 text-center text-xs text-slate-400">{day}</span>)}{Array.from({length:offset}).map((_,index)=><span key={`empty-${index}`}/>)}{Array.from({length:count},(_,index)=>{const value=`${year}-${String(month).padStart(2,'0')}-${String(index+1).padStart(2,'0')}`,day=new Date(`${value}T00:00:00Z`).getUTCDay(),inRange=value>=startDate&&value<=endDate,holiday=holidays.has(value),work=inRange&&!holiday&&workDays.includes(day);return <span title={holidays.get(value)?.name||''} key={value} className={`flex aspect-square items-center justify-center rounded-lg text-xs ${holiday?'bg-amber-100 text-amber-700':work?'bg-blue-100 text-blue-700':inRange?'bg-slate-100 text-slate-400':'text-slate-300'}`}>{index+1}</span>})}</div><div className="mt-3 flex gap-2 text-xs"><span className="rounded-lg bg-blue-100 px-2 py-1 text-blue-700">Jadwal dibuat</span><span className="rounded-lg bg-amber-100 px-2 py-1 text-amber-700">Libur nasional</span></div></section>;
}
