import {useEffect,useState} from 'react';
import {api} from '../../lib/apiClient';
import {type Crew,money,button,primary,control,panel,message} from './adminData';
import {DataTable,MiniChart,Stat} from './adminWidgets';
import {type PayrollAttendance,type PayrollContext,type PayrollRow,type PayrollRules,estimatePayroll,monthKeys,payrollSheet,getPayrollRules,rememberPayrollRules} from './payrollData';
import {downloadWorkbook} from '../../lib/xlsxExport';
import Modal from '../../components/ui/Modal';
export default function PayrollWorkspace(){
 const [crew,setCrew]=useState<Crew[]>([]),[logs,setLogs]=useState<PayrollAttendance[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [month,setMonth]=useState(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(new Date()).slice(0,7)),[search,setSearch]=useState(''),[kind,setKind]=useState(''),[detail,setDetail]=useState<PayrollRow|null>(null);
 const [payrollContext,setPayrollContext]=useState<PayrollContext>({schedules:[],permissions:[]});
 const [rules,setRulesState]=useState<PayrollRules>(getPayrollRules);
 const setRules=(next:PayrollRules|((previous:PayrollRules)=>PayrollRules))=>setRulesState(previous=>{const value=typeof next==='function'?next(previous):next;rememberPayrollRules(value);return value;});
 async function load(){setLoading(true);setError('');try{const [c,a,p]=await Promise.all([api.get<Crew[]>('/crew'),api.get<{registered:PayrollAttendance[]}>('/admin-attendance'),api.get<PayrollContext>(`/admin-store-schedules/payroll-context?month=${month}`)]);setCrew(c);setLogs(a.registered);setPayrollContext(p);}catch(e){setError(message(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[month]);
 const rows=estimatePayroll(crew,logs,month,rules,payrollContext).filter(r=>(!kind||r.crew.crew_type===kind)&&[r.crew.user.full_name,r.crew.user.email].join(' ').toLowerCase().includes(search.toLowerCase().trim()));
 const sum=(k:'total'|'bonus'|'deduction'|'lateHours'|'overtimeHours')=>rows.reduce((n,r)=>n+r[k],0);
 async function pdf(list:PayrollRow[]){try{const {jsPDF}=await import('jspdf');const {default:autoTable}=await import('jspdf-autotable');const doc=new jsPDF({orientation:'landscape'});doc.setFontSize(15);doc.text(`Jawara - Simulasi Payroll ${month}`,14,16);doc.setFontSize(9);doc.text('Estimasi, bukan bukti pembayaran. Gaji dan tarif saat ini. Guest tidak termasuk.',14,23);const sheet=payrollSheet(list,month,rules);autoTable(doc,{startY:29,head:[sheet[0]],body:sheet.slice(1),styles:{fontSize:6},headStyles:{fillColor:[21,84,223]}});doc.save(`Payroll-${month}.pdf`);}catch(e){setError(message(e));}}
 const actions=(list:PayrollRow[])=> <div className="flex flex-wrap gap-2"><button disabled={loading||!!error||!list.length} className={button} onClick={()=>downloadWorkbook(payrollSheet(list,month,rules),`Payroll-${month}.xlsx`)}>Export Excel</button><button disabled={loading||!!error||!list.length} className={primary} onClick={()=>void pdf(list)}>Export PDF</button></div>;
 return <div className="p-4 sm:p-6 space-y-5"><div className="flex justify-between gap-3"><h2 className="text-lg font-bold text-slate-900">Payroll Crew</h2><button className={button} disabled={loading} onClick={()=>void load()}>Muat ulang</button></div>{error&&<p role="alert" className="ui-error p-4 rounded-xl">{error}</p>}
 <div className="grid sm:grid-cols-3 gap-4"><Stat label="Total Estimasi Payroll" value={loading?'...':money(sum('total'))} sub={`${rows.length} crew`}/><Stat label="Total Bonus Lembur" value={money(sum('bonus'))} sub={`${sum('overtimeHours')} jam disetujui`} tone="green"/><Stat label="Total Potongan" value={money(sum('deduction'))} sub={`${sum('lateHours')} jam telat, termasuk potongan absen`} tone="red"/></div>
 <details className={panel}><summary className="text-sm font-semibold cursor-pointer text-slate-900">Aturan simulasi payroll</summary><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-4">{(['eventBasis','storeBasis'] as const).map(key=><label className="text-xs text-slate-600" key={key}>{key==='eventBasis'?'Dasar gaji Event':'Dasar gaji Store'}<select className={control} value={rules[key]} onChange={e=>setRules(r=>({...r,[key]:e.target.value}))}><option value="MONTHLY">Per bulan (tanpa prorata)</option><option value="PER_ATTENDANCE">Per absensi lengkap sah</option></select></label>)}{(['lateRate','overtimeRate'] as const).map(key=><label className="text-xs text-slate-600" key={key}>{key==='lateRate'?'Potongan / jam (Rp)':'Bonus lembur / jam (Rp)'}<input className={control} inputMode="numeric" value={rules[key]} onFocus={e=>e.target.select()} onChange={e=>{if(/^\d{0,7}$/.test(e.target.value))setRules(r=>({...r,[key]:Number(e.target.value)}));}}/></label>)}</div><p className="text-xs text-slate-500 mt-3">Aturan ini hanya untuk simulasi pada sesi ini dan ikut dicatat dalam ekspor. Tarif belum menjadi kebijakan payroll tersimpan.</p></details>
 <div className="flex flex-wrap justify-between gap-3"><div className="flex flex-wrap gap-3"><input aria-label="Periode payroll" type="month" className={control+' !w-auto'} value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/><select aria-label="Jenis payroll" className={control+' !w-auto'} value={kind} onChange={e=>setKind(e.target.value)}><option value="">Semua jenis</option><option value="CREW_EVENT">Event</option><option value="CREW_STORE">Store</option></select><input aria-label="Cari payroll" className={control+' !w-auto'} placeholder="Cari nama atau email..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{actions(rows)}</div>
 {loading?<p>Memuat payroll...</p>:<DataTable headers={['Nama','Jenis','Gaji Pokok','Absen','Jam Telat','Total Potongan','Jam Lembur','Bonus Lembur','Estimasi Payroll','Aksi']} rows={rows.map(r=>[r.crew.user.full_name,r.crew.crew_type==='CREW_EVENT'?'Event':'Store',<span>{money(r.base)}<small className="block text-xs">{r.units} × {money(r.baseRate)}</small></span>,r.crew.crew_type==='CREW_STORE'?`${r.absentDays} hari`:'—',`${r.lateHours} jam`,<span className="text-red-700">-{money(r.deduction)}</span>,`${r.overtimeHours} jam`,<span className="text-emerald-700">+{money(r.bonus)}</span>,<strong>{money(r.total)}</strong>,<button className="text-blue-700" onClick={()=>setDetail(r)}>Detail</button>])}/>} 
 <Modal open={!!detail} onClose={()=>setDetail(null)} title={`Detail Payroll${detail?' • '+detail.crew.user.full_name:''}`} size="lg">{detail&&<div className="space-y-4"><div className="grid grid-cols-2 gap-3"><Stat label="Gaji Pokok" value={money(detail.base)}/><Stat label="Total Potongan" value={'-'+money(detail.deduction)} tone="red"/><Stat label="Bonus Lembur" value={money(detail.bonus)} tone="green"/><Stat label="Estimasi Payroll" value={money(detail.total)} tone="plain"/></div><DataTable headers={['Rincian Perhitungan',month]} rows={[[`Gaji (${detail.units} × ${money(detail.baseRate)})`,money(detail.base)],[`Bonus (${detail.overtimeHours} jam × ${money(rules.overtimeRate)})`,money(detail.bonus)],[`Potongan absen (${detail.absentDays} dari ${detail.scheduledDays} hari kerja)`,'-'+money(detail.absenceDeduction)],[`Potongan telat (${detail.lateHours} jam × ${money(rules.lateRate)})`,'-'+money(detail.lateDeduction)],['Total estimasi',money(detail.total)]]}/><p className="text-xs text-slate-500">{detail.excluded} catatan tidak lengkap, belum disetujui, atau bukan kehadiran sah tidak dimasukkan. Riwayat pembayaran final belum tersedia.</p><MiniChart title="Tren lembur disetujui" subtitle="6 bulan, dari absensi server. Bukan riwayat pembayaran." points={monthKeys(month).map(m=>({label:m.slice(5),value:estimatePayroll([detail.crew],logs,m,rules)[0]?.overtimeHours||0}))}/>{actions([detail])}</div>}</Modal></div>;
}
