import ShiftFields from '../../components/attendance/ShiftFields';
import {t as translateUI} from '../../lib/i18n';
import {submitScheduleRange} from '../../lib/scheduleRange';
import {useEffect,useState,type FormEvent} from 'react';
import AttendanceCalendar from '../../components/attendance/AttendanceCalendar';
import {api} from '../../lib/apiClient';
import {button,control,message,primary} from './adminData';

interface Schedule {shift_number?:number;id:string;schedule_date:string;start_time:string;end_time:string;late_tolerance_minutes:number;overtime_preapproved:boolean}
interface Response {assignment:{id:string;start_date:string;end_date:string|null;store:{name:string}}|null;schedules:Schedule[]}
interface RangeResult {warnings?:string[];created:number;skippedOverlap?:number;skippedHoliday:number;skippedExisting:number;skippedEvent:number;skippedDay:number}
const currentMonth=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit'}).format(new Date()).slice(0,7);
const DAY_OPTIONS=[{value:0,label:'Min'},{value:1,label:'Sen'},{value:2,label:'Sel'},{value:3,label:'Rab'},{value:4,label:'Kam'},{value:5,label:'Jum'},{value:6,label:'Sab'}];
const emptyForm={startDate:'',endDate:'',shiftNumber:1,startTime:'09:00',endTime:'18:00',lateToleranceMinutes:'0',overtimePreapproved:false,workDays:[1,2,3,4,5,6]};

export default function StoreScheduleManager({crewId,crewName}:{crewId:string;crewName:string}){
 const [month,setMonth]=useState(currentMonth()),[data,setData]=useState<Response|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [form,setForm]=useState(emptyForm),[editingDate,setEditingDate]=useState<string|null>(null);
 async function load(){setBusy(true);setError('');try{setData(await api.get<Response>(`/admin-store-schedules/crew/${crewId}?month=${month}`));}catch(e){setError(message(e));}finally{setBusy(false);}}
 useEffect(()=>{void load();},[crewId,month]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{
   if(editingDate){await api.post('/admin-store-schedules',{crewId,scheduleDate:editingDate,shiftNumber:form.shiftNumber,startTime:form.startTime,endTime:form.endTime,lateToleranceMinutes:Number(form.lateToleranceMinutes),overtimePreapproved:form.overtimePreapproved});setNotice(`Jadwal ${editingDate} diperbarui.`);}
   else{const result=await submitScheduleRange(body=>api.post<RangeResult>('/admin-store-schedules/range',body),{crewId,...form,lateToleranceMinutes:Number(form.lateToleranceMinutes)},setNotice);setNotice(`${result.created} jadwal dibuat. ${result.skippedHoliday} tanggal libur, ${result.skippedExisting} jadwal lama, dan ${result.skippedEvent} benturan event dan ${result.skippedOverlap||0} shift bertumpuk dilewati. ${(result.warnings||[]).join(' ')}`);}
   setEditingDate(null);setForm(emptyForm);await load();
 }catch(e){setError(message(e));}finally{setBusy(false);}}
 function edit(s:Schedule){setEditingDate(s.schedule_date);setForm({...emptyForm,shiftNumber:s.shift_number||1,startDate:s.schedule_date,endDate:s.schedule_date,startTime:s.start_time.slice(0,5),endTime:s.end_time.slice(0,5),lateToleranceMinutes:String(s.late_tolerance_minutes||0),overtimePreapproved:!!s.overtime_preapproved});}
 function toggleDay(day:number){setForm(previous=>({...previous,workDays:previous.workDays.includes(day)?previous.workDays.filter(value=>value!==day):[...previous.workDays,day].sort()}));}
 return <div className="space-y-5">
  <p className="text-sm text-slate-600">{translateUI("Buat jadwal") + " "}<strong>{crewName}</strong>{" " + translateUI("berdasarkan shift dan rentang tanggal. Ubah jadwal per tanggal untuk mengganti shift yang sudah ada.")}</p>
  {error&&<p role="alert" className="ui-error p-3 rounded-xl text-sm">{translateUI(error)}</p>}{notice&&<p role="status" className="ui-success p-3 rounded-xl text-sm">{translateUI(notice)}</p>}
  <label className="block text-xs text-slate-600">{translateUI("Bulan kalender")}<input aria-label={translateUI("Bulan jadwal Store")} type="month" className={control+' !w-auto'} value={month} onChange={e=>setMonth(e.target.value)}/></label>
  {data&&!data.assignment?<p className="bg-amber-50 text-amber-800 p-3 rounded-xl text-sm">{translateUI("Belum ada lokasi kerja aktif pada bulan ini.")}</p>:data?.assignment&&<p className="text-sm text-slate-700">{translateUI("Lokasi kerja:") + " "}<strong>{data.assignment.store.name}</strong> • {data.assignment.start_date}{data.assignment.end_date?` sampai ${data.assignment.end_date}`:''}</p>}
  <form onSubmit={save} className="grid sm:grid-cols-2 gap-3 border border-slate-200 rounded-xl p-4">
   <div className="sm:col-span-2 flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-slate-900">{editingDate?`Edit jadwal ${editingDate}`:translateUI("Buat jadwal rentang")}</strong>{editingDate?<button type="button" className={button} onClick={()=>{setEditingDate(null);setForm(emptyForm);}}>{translateUI("Batal edit")}</button>:null}</div>
   <label className="text-xs text-slate-600">{translateUI("Tanggal mulai")}<input required disabled={!!editingDate} type="date" className={control} value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label>
   <label className="text-xs text-slate-600">{translateUI("Tanggal selesai")}<input required disabled={!!editingDate} min={form.startDate} type="date" className={control} value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label>
   {!editingDate?<fieldset className="sm:col-span-2"><legend className="text-xs text-slate-600 mb-2">{translateUI("Hari kerja")}</legend><div className="flex flex-wrap gap-2">{DAY_OPTIONS.map(day=><label key={day.value} className={`cursor-pointer rounded-xl border px-3 py-2 text-sm ${form.workDays.includes(day.value)?'border-blue-500 bg-blue-50 text-blue-700':'border-slate-200 text-slate-500'}`}><input type="checkbox" className="sr-only" checked={form.workDays.includes(day.value)} onChange={()=>toggleDay(day.value)}/>{day.label}</label>)}</div></fieldset>:null}
   <ShiftFields shiftNumber={form.shiftNumber} startTime={form.startTime} endTime={form.endTime} disabled={busy} onChange={patch=>setForm({...form,...patch})}/>
   <label className="text-xs text-slate-600 sm:col-span-2">{translateUI("Toleransi telat (menit)")}<input required type="number" min="0" max="240" className={control} value={form.lateToleranceMinutes} onChange={e=>setForm({...form,lateToleranceMinutes:e.target.value})}/></label>
   <label className="sm:col-span-2 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><input aria-label={translateUI("Setujui lembur dari jadwal")} type="checkbox" className="mt-1" checked={form.overtimePreapproved} onChange={e=>setForm({...form,overtimePreapproved:e.target.checked})}/><span><strong>{translateUI("Setujui lembur dari jadwal")}</strong><small className="block mt-1">{translateUI("Jam penuh setelah jam pulang langsung disetujui. Jika tidak dicentang, lembur menunggu admin.")}</small></span></label>
   <button disabled={busy||form.startTime===form.endTime||!data?.assignment||(!editingDate&&!form.workDays.length)} className={primary+' sm:col-span-2'}>{busy?translateUI("Menyimpan..."):editingDate?translateUI("Simpan Perubahan"):translateUI("Buat Jadwal Rentang")}</button>
  </form>
  <AttendanceCalendar key={data?.schedules.map(s=>`${s.id}:${s.shift_number}:${s.start_time}:${s.end_time}`).join()} crewId={crewId}/>
  <div className="hidden sm:block border border-slate-200 rounded-xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-600"><tr><th className="p-3 text-left">{translateUI("Tanggal")}</th><th className="p-3 text-left">Shift</th><th className="p-3 text-left">{translateUI("Jam WIB")}</th><th className="p-3 text-left">{translateUI("Toleransi")}</th><th className="p-3 text-left">{translateUI("Lembur")}</th><th className="p-3 text-left">{translateUI("Aksi")}</th></tr></thead><tbody className="divide-y divide-slate-100">{data?.schedules.map(s=><tr key={s.id}><td className="p-3">{s.schedule_date}</td><td className="p-3 whitespace-nowrap">Shift {s.shift_number||1}</td><td className="p-3">{s.start_time.slice(0,5)}–{s.end_time.slice(0,5)}{s.end_time<s.start_time&&<small className="block text-blue-700">Pulang besok</small>}</td><td className="p-3">{s.late_tolerance_minutes||0}{" " + translateUI("menit")}</td><td className="p-3">{s.overtime_preapproved?<span className="text-emerald-700">{translateUI("Disetujui")}</span>:<span className="text-slate-500">{translateUI("Perlu tinjauan")}</span>}</td><td className="p-3"><button className={button} type="button" onClick={()=>edit(s)}>{translateUI("Ubah")}</button></td></tr>)}</tbody></table>{data&&!data.schedules.length&&<p className="p-5 text-sm text-center text-slate-500">{translateUI("Belum ada jadwal pada bulan ini.")}</p>}</div>
  <div className="sm:hidden space-y-3">{data?.schedules.map(s=><article key={s.id} className="rounded-xl border border-slate-200 p-4 space-y-2"><div className="flex justify-between gap-2"><strong className="text-sm">{s.schedule_date}</strong><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">Shift {s.shift_number||1}</span></div><p className="text-sm">{s.start_time.slice(0,5)} – {s.end_time.slice(0,5)} WIB{s.end_time<s.start_time?' · Pulang besok':''}</p><p className="text-xs text-slate-500">Toleransi {s.late_tolerance_minutes||0} menit · Lembur {s.overtime_preapproved?'disetujui':'perlu tinjauan'}</p><button className={button+' w-full min-h-11'} type="button" onClick={()=>edit(s)}>Ubah jadwal</button></article>)}{data&&!data.schedules.length&&<p className="text-sm text-slate-500 text-center">Belum ada jadwal pada bulan ini.</p>}</div>
 </div>;
}
